### PR TITLE
added text converter

### PR DESCRIPTION
**Pull request by dhruv1345**
Hi I have added the text converter so as to add another project in a well maintained repo.

Hope my contribution help users.

Thank you.

### CODE REVIEW

**Comment by dhruv1345** [comment]
Hoping for a nice response.

**Comment by dhruv1345** [comment]
I have made the changes. Now i hope it is in a condition to be merged.

**Comment by keshavgbpecdelhi** [comment]
Thankyou for your time and efforts @dhruv1345.

**Comment by keshavgbpecdelhi** [comment]
#307

**Pull request merged**
