### PR TITLE
Added Basic Responsive Bootstrap Website

### PR DESCRIPTION
**Pull request by kishanlalchoudhary**
Added A basic , responsive website made using bootstrap
which consists of aboutus, contactus, landingpage, navigationbar, footer, ourservices, gallery

### CODE REVIEW

**Comment by keshavgbpecdelhi** [comment]
Thanks for contribution and reaching out on LinkedIn. You just need to little patient. 😊

**Comment by keshavgbpecdelhi** [comment]
#253 done

**Comment by kishanlalchoudhary** [comment]
I* started

**Comment by kishanlalchoudhary** [comment]
Happy Hacking

**Pull request merged**
