### PR TITLE
Added E-commerce Anime site

### PR DESCRIPTION
**Pull request by omk-coder**
Issue No: #93

### CODE REVIEW

**Comment by keshavgbpecdelhi** [comment]
Can you check the README.MD again I think you haven't made the table properly.

**Comment by keshavgbpecdelhi** [comment]
Ok I will do it manually, merging this one.

**Comment by omk-coder** [comment]
thanks keshav to let me contribute on this issue. Its an very unique idea to have other projects together in one repo.

**Comment by Ishukumarpathak** [comment]
> Issue No: #93

Hey omk-coder i want to make some changes in your project

**Pull request merged**
