### PR TITLE
tailwindcss-404pages

### PR DESCRIPTION
**Pull request by Alidhuniya**
# Issue No. (#80)

# Screenshots
Screenshot (318)
Screenshot (319)
Screenshot (320)

### CODE REVIEW

**Comment by keshavgbpecdelhi** [comment]
@Alidhuniya can you please change that 404-collection directory to only make a single directory of 404-error then add index.html into it. Hope you get it!

**Comment by Alidhuniya** [comment]
> @Alidhuniya can you please change that 404-collection directory to only make a single directory of 404-error then add index.html into it. Hope you get it!

Ok, I will do it sir. In the project there is one index.html and other linked HTML file into main index.html. so I should only change the directory yes

**Comment by Alidhuniya** [comment]
> @Alidhuniya can you please change that 404-collection directory to only make a single directory of 404-error then add index.html into it. Hope you get it!

I have made changes as you want. please look at it

**Comment by keshavgbpecdelhi** [comment]
Awesome work. Thanks for contributing @Alidhuniya 🔥

**Pull request merged**
